Feature/file selection
tkambler/electron-preferences pull request #84
Opened 2021-07-06 16:11 UTC by pvrobays

added the new file type, which is able to multi-select files. See the extended example preferences for config.

2021-07-06 16:12 UTC, pvrobays commented
TODO:
- [ ] Test
- [ ] add usage to README
- [ ] update CHANGELOG

2021-07-06 16:12 UTC, pvrobays commented
closes #55

2021-07-07 20:03 UTC, lacymorrow requested changes
Looks great! There are a few changes I requested but overall an awesome addition

2021-07-07 20:03 UTC, lacymorrow commented on src/app/components/main/components/group/components/fields/file/index.js
> +        const { multiSelections, value, help, label } = this;
You have two variables named `multiSelections`, they're in two different scopes but one scope receives both variables, plus it's confusing in this context.

You can just define the vars at the top of the render method and use them throughout.

2021-07-08 15:42 UTC, pvrobays commented on src/app/utils/isArray.js
> +    return Array.isArray(obj);
I know, my most helpful util function ever! 😅

2021-07-08 16:01 UTC, pvrobays commented
@lacymorrow FYI. Fixed your PR remarks and added the ability to have multi selection for a directory as well.
Closes #81

2021-07-08 17:37 UTC, lacymorrow approved these changes
LGTM++

2021-07-10 18:47 UTC, merged

2021-07-10 18:48 UTC, pvrobays commented
Merged. FYI @lacymorrow I've had some issues with my OCD with the linting settings, changed these things:
- No spaces between parentheses
- Always end with semicolon